apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tekton-deployment
  namespace: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: my-tekton-app
  template:
    metadata:
      labels:
        app: my-tekton-app
    spec:
      containers:
      - name: my-tekton-app
        image: __IMAGE__
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"